[package]
name = "tcc-trace"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# aya = { version = "0.11.0", features=["async_tokio"], git = "https://github.com/aya-rs/aya" }
aya = "0.10.0"
aya-log = {  git = "https://github.com/aya-rs/aya" }
bytes = "1"
tcc-trace-common = { path = "../tcc-trace-common", features=["user"] }
anyhow = "1.0.42"
clap = { version = "3.1", features = ["derive"] }
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
socket2 = "*"
libc = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nix = { version = "*", features = ["socket","net"] }

[[bin]]
name = "tcc-trace"
path = "src/main.rs"
